apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitec-backend
  labels:
    app: capitec-user-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capitec-backend
  template:
    metadata:
      labels:
        app: capitec-backend
    spec:
      containers:
        - name: backend
          image: thapeloseema/capitec-user-service:backend-amd64
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"