apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitec-postgres
  labels:
    app: capitec-user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capitec-postgres
  template:
    metadata:
      labels:
        app: capitec-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"